on:
  push:
    branches: [main]

env:
  REGISTRY: git.fayzullaev.ca
  IMAGE: git.fayzullaev.ca/${{ github.repository }}:latest

jobs:
  deploy:
    runs-on: docker
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    container:
      image: docker:cli
    steps:
      - name: Install dependencies
        run: apk add --no-cache git openssh-client curl jq

      - name: Checkout
        env:
          TOKEN: ${{ github.token }}
        run: |
          git clone --depth 1 --branch "$GITHUB_REF_NAME" \
            "https://oauth2:${TOKEN}@${REGISTRY}/${GITHUB_REPOSITORY}.git" .

      - name: Build and push
        run: |
          SHORT_SHA=$(echo "$GITHUB_SHA" | cut -c1-7)
          IMAGE_SHA="${REGISTRY}/${GITHUB_REPOSITORY}:sha-${SHORT_SHA}"
          echo "${{ secrets.REGISTRY_TOKEN }}" | docker login "$REGISTRY" -u "${{ github.actor }}" --password-stdin
          docker build -t "$IMAGE" -t "$IMAGE_SHA" .
          docker push "$IMAGE"
          docker push "$IMAGE_SHA"

      - name: Deploy to VPS
        env:
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          mkdir -p ~/.ssh
          echo "$VPS_SSH_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh -o StrictHostKeyChecking=accept-new -i ~/.ssh/deploy_key "${DEPLOY_USER}@${VPS_HOST}" \
            "bash -c 'docker pull ${IMAGE} && cd ~/docker/${REPO_NAME} && docker compose up -d'"

      - name: Verify deployment
        env:
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          sleep 10
          ssh -o StrictHostKeyChecking=accept-new -i ~/.ssh/deploy_key "${DEPLOY_USER}@${VPS_HOST}" \
            "bash -c 'for i in 1 2 3 4 5; do \
              curl -sf http://localhost:8080/health > /dev/null && echo \"Health check passed\" && exit 0; \
              echo \"Attempt \$i: health check failed, retrying in 10s...\"; sleep 10; \
            done; echo \"Health check failed after 5 attempts\"; exit 1'"

      - name: Notify deploy succeeded
        if: success()
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          SHORT_SHA=$(echo "$GITHUB_SHA" | cut -c1-7)
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d parse_mode="Markdown" \
            -d text="*Deployed* -- \`${REPO_NAME}\` (\`sha-${SHORT_SHA}\`)
          [View commit](https://git.fayzullaev.ca/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA})"

      - name: Notify deploy failed
        if: failure()
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d chat_id="${TELEGRAM_CHAT_ID}" \
            -d parse_mode="Markdown" \
            -d text="*Deploy FAILED* -- \`${REPO_NAME}\`
          [View run](https://git.fayzullaev.ca/${GITHUB_REPOSITORY}/actions)"
